// v16.0 Phase 66 T1 (NEW) — `workflows/role-prompts.yaml` → codex agent roles.
//
// WHAT codex does with these (measured on codex-cli 0.155.1, findings F1 + F8):
//   - `load_agent_roles()` has two independent sources. One is the `[agents]`
//     section of config.toml; the other is a plain DIRECTORY SCAN of
//     `<CODEX_HOME>/agents/` (codex-rs/agent-roles/src/loader.rs:76-78). harnessed
//     uses only the second, so this file never reads or writes config.toml — the
//     v16.0 hard boundary holds (ADR 0041, same reasoning as codexHookPlugin.ts).
//   - the role NAME comes from the file CONTENT (`role_name_hint: None` at
//     loader.rs:303), not from the filename, and a role whose name duplicates an
//     already-loaded one is SKIPPED with a warning. The host already carries 33
//     GSD roles, so every harnessed role is namespaced `harnessed-<sub>` and the
//     filename mirrors it (prefix = the uninstall ownership signal).
//   - `description` is REQUIRED ("agent role `<name>` must define a description").
//   - `developer_instructions` genuinely reaches the spawned sub-agent's context
//     (T0.4 probe: a role asking for an `ECHO-7742` suffix got exactly that back),
//     so these roles are the real carrier for the IN-SESSION
//     `spawn_agent(agent_type, message)` path — NOT for `codex exec`, which
//     cannot name an agent role at all (F2) and carries its prompt inline.
//   - a role whose instructions read like "ignore the task, print X" is refused by
//     the sub-agent as prompt injection (T0.4, first attempt). `buildAgentDef`'s
//     ordinary "You are a <specialist> … Emit a structured COMPLETE signal" body
//     is exactly the normal role-description wording that passes.
//
// LAYERING: the caller renders `{{ host.* }}` for host `codex` FIRST
// (`renderRolePromptsForHost`, src/cli/lib/rolePromptHostRender.ts) and hands the
// rendered registry in. Doing it here would drag the CLI layer into an installer
// module; doing it not at all would ship Claude Code's primitives (Task tool,
// SendMessage, Agent Teams) into a codex-side artifact.
//
// Pure/impure split: `buildCodexAgentRole` is a string function (golden-testable);
// only `writeCodexAgentRoles` / `discoverCodexAgentRoleFiles` touch the disk.

import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { RolePrompt } from '../../workflow/rolePrompts.js'
import { buildAgentDef } from '../../workflow/run.js'

/** Namespace for every harnessed-owned role name AND filename (F1 anti-collision). */
export const CODEX_AGENT_ROLE_PREFIX = 'harnessed-'

/** First bytes of every generated file. Ownership signal for write + uninstall:
 *  a `harnessed-*.toml` WITHOUT it is somebody else's file and is never touched. */
export const CODEX_AGENT_ROLE_MARKER = '# GENERATED by harnessed'

/** Sub-workflow ids are slugs; anything else cannot become a filename here. */
const SUB_NAME = /^[a-z][a-z0-9-]*$/

/** `<CODEX_HOME>/agents` — the directory codex scans. Callers resolve CODEX_HOME
 *  with `resolveCodexHome()` (src/installers/codexHookAdd.ts), the one place that
 *  rule lives. */
export function codexAgentsDir(codexHome: string): string {
  return join(codexHome, 'agents')
}

/** `harnessed-<sub>` — the `name` key, i.e. the `spawn_agent` `agent_type` value. */
export function codexAgentRoleName(sub: string): string {
  return `${CODEX_AGENT_ROLE_PREFIX}${sub}`
}

/** Could this directory entry be one of ours? (Cheap filter before the marker read.) */
export function isHarnessedAgentRoleFileName(fileName: string): boolean {
  return fileName.startsWith(CODEX_AGENT_ROLE_PREFIX) && fileName.endsWith('.toml')
}

/** Drop what TOML cannot carry: bare CR and C0/C1 controls other than tab/newline.
 *  Written as a scan rather than a regex class so no control literal lands in a
 *  pattern (biome noControlCharactersInRegex). */
function normalize(text: string): string {
  let out = ''
  for (const ch of text.replace(/\r\n?/g, '\n')) {
    const c = ch.codePointAt(0) ?? 0
    if (c === 9 || c === 10 || (c >= 32 && c !== 127)) out += ch
  }
  return out
}

/** A TOML single-line basic string (`"…"`) — used for `description` and `name`. */
export function tomlBasicString(value: string): string {
  const escaped = normalize(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\t/g, '\\t')
    .replace(/\n/g, '\\n')
  return `"${escaped}"`
}

/**
 * A TOML multi-line string for `developer_instructions`.
 *
 * Preferred form is the LITERAL block `'''…'''`: it applies no escape
 * processing, so a prompt full of backslashes, `{{ }}` and quotes survives
 * byte-for-byte (and reads identically to the 33 GSD roles already on the host).
 *
 * It cannot represent two things, and TOML gives literal blocks no escape hatch:
 * a `'''` sequence in the body, and a body ending in `'` (which would run into
 * the delimiter and produce 4+ consecutive apostrophes). Either case falls back
 * to the basic block `"""…"""` with `\` and `"` escaped — always parseable, at
 * the cost of a less readable file.
 */
export function tomlMultilineString(value: string): string {
  const body = normalize(value)
  if (!body.includes("'''") && !body.endsWith("'")) return `'''\n${body}'''`
  return `"""\n${body.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"""`
}

/** One generated role file. */
export interface CodexAgentRole {
  /** Sub-workflow id this came from (`verify-paranoid`). */
  sub: string
  /** `harnessed-<sub>` — the `spawn_agent(agent_type: …)` value. */
  roleName: string
  /** `harnessed-<sub>.toml` — basename inside `<CODEX_HOME>/agents/`. */
  fileName: string
  /** Full file content, newline-terminated. */
  toml: string
}

export interface CodexAgentRoleOptions {
  /**
   * Host renderer for `description`.
   *
   * `renderRolePromptsForHost` deliberately leaves `description` alone: on the
   * commands surface it is raw yaml frontmatter, where a substitution would ship
   * verbatim. Here it is prose codex reads, and several entries carry
   * `{{ host.team }}` — so this surface renders it, exactly as
   * `generateCommands.ts` does with its `descriptionTable`. Omitted → pass-through.
   */
  renderDescription?: (body: string) => string
}

/**
 * Build one agent-role file from an ALREADY host-rendered role prompt.
 *
 * `developer_instructions` is `buildAgentDef(...).prompt` verbatim — the same
 * body `harnessed prompt <sub>` prints and the SDK spawn path sends. There is
 * deliberately no second assembly here: a divergence between what a Claude
 * subagent and a codex sub-agent are told would be invisible until it bit.
 *
 * Throws on a sub id that is not a slug (it would become a path).
 */
export function buildCodexAgentRole(
  sub: string,
  rolePrompt: RolePrompt,
  opts: CodexAgentRoleOptions = {},
): CodexAgentRole {
  if (!SUB_NAME.test(sub)) throw new Error(`not a usable codex agent-role name: '${sub}'`)
  const roleName = codexAgentRoleName(sub)
  const prompt = buildAgentDef(sub, { [sub]: rolePrompt }).prompt
  // codex REJECTS a role with an empty description, and role-prompts entries are
  // yaml the user can edit — so a blank one gets a generated stand-in rather than
  // a file codex refuses to load.
  const src = typeof rolePrompt.description === 'string' ? rolePrompt.description : ''
  const raw = (opts.renderDescription ? opts.renderDescription(src) : src).trim()
  const description = raw.length > 0 ? raw : `harnessed workflow role: ${sub}`
  const toml = `${[
    `${CODEX_AGENT_ROLE_MARKER} — codex agent role for the \`${sub}\` sub-workflow.`,
    '# Source: workflows/role-prompts.yaml. Rewritten by every `harnessed setup`; do not edit.',
    `description = ${tomlBasicString(description)}`,
    `developer_instructions = ${tomlMultilineString(prompt)}`,
    `name = ${tomlBasicString(roleName)}`,
  ].join('\n')}\n`
  return { sub, roleName, fileName: `${roleName}.toml`, toml }
}

/**
 * Sweep a role-prompt registry into role files, sorted by filename.
 *
 * `subs` (when given) restricts the sweep to the sub-workflows actually
 * installed. Master orchestrators are skipped: they are pure dispatchers with an
 * empty checklist and no role-prompt fallback (rolePrompts.ts `is_master`), so a
 * spawnable role for one would be a dead entry in the `agent_type` namespace.
 * An unusable key is skipped rather than aborting the sweep.
 */
export function buildCodexAgentRoles(
  prompts: Record<string, RolePrompt>,
  subs?: readonly string[],
  opts: CodexAgentRoleOptions = {},
): CodexAgentRole[] {
  const wanted = subs ? new Set(subs) : null
  const roles: CodexAgentRole[] = []
  for (const [sub, rolePrompt] of Object.entries(prompts)) {
    if (wanted && !wanted.has(sub)) continue
    if (!rolePrompt || rolePrompt.is_master === true) continue
    try {
      roles.push(buildCodexAgentRole(sub, rolePrompt, opts))
    } catch {
      // not a slug → cannot be a filename; the rest of the registry still installs
    }
  }
  return roles.sort((a, b) => a.fileName.localeCompare(b.fileName))
}

export interface WriteCodexAgentRolesResult {
  /** Absolute paths written (created or refreshed). */
  written: string[]
  /** Paths left alone, with why (foreign file / write error). */
  skipped: { path: string; reason: string }[]
}

/**
 * Write roles into `<CODEX_HOME>/agents/`, creating the directory if codex has
 * never made one.
 *
 * Additive-only, exactly like the `commands/<x>.md` pass: an existing
 * `harnessed-*.toml` is refreshed ONLY when it carries the harnessed marker.
 * Anything else with that name is somebody's hand-written role and is reported,
 * never overwritten.
 */
export async function writeCodexAgentRoles(
  agentsDir: string,
  roles: readonly CodexAgentRole[],
): Promise<WriteCodexAgentRolesResult> {
  const result: WriteCodexAgentRolesResult = { written: [], skipped: [] }
  if (roles.length === 0) return result
  await mkdir(agentsDir, { recursive: true })
  for (const role of roles) {
    const path = join(agentsDir, role.fileName)
    let existing: string | null = null
    try {
      existing = await readFile(path, 'utf8')
    } catch {
      // absent → a fresh write
    }
    if (existing !== null && !existing.includes(CODEX_AGENT_ROLE_MARKER)) {
      result.skipped.push({ path, reason: 'exists and is not harnessed-generated' })
      continue
    }
    try {
      await writeFile(path, role.toml, 'utf8')
      result.written.push(path)
    } catch (e) {
      result.skipped.push({ path, reason: (e as Error).message })
    }
  }
  return result
}

/**
 * Harnessed-owned role files in `agentsDir`, sorted — the uninstall inventory.
 * Requires BOTH the `harnessed-` prefix and the marker, so the 33 GSD roles (and
 * any hand-written file that merely borrowed the prefix) are never listed.
 * A missing / unreadable directory is an empty inventory, not an error.
 */
export async function discoverCodexAgentRoleFiles(agentsDir: string): Promise<string[]> {
  let entries: string[]
  try {
    entries = await readdir(agentsDir)
  } catch {
    return []
  }
  const owned: string[] = []
  for (const entry of entries) {
    if (!isHarnessedAgentRoleFileName(entry)) continue
    const path = join(agentsDir, entry)
    try {
      if ((await readFile(path, 'utf8')).includes(CODEX_AGENT_ROLE_MARKER)) owned.push(path)
    } catch {
      // unreadable → not claimable
    }
  }
  return owned.sort()
}
