// `~/.codex/AGENTS.md` 的 harnessed 区间 —— codex 在会话开始时读这个文件。
//
// 问题:维护者把 CLAUDE.md 手抄进了 AGENTS.md,然后它漂了 —— 实测那份 192 行的副本里
// `/to-prd` / `/to-issues` / `/diagnose` / `/zoom-out` 全是上游已改名或已删的;两个已被
// Claude Code 删除的 Agent-Teams 建团 / 删团工具也还在(名字刻意不抄进本文件 ——
// `tests/workflow/agentTeamsApiMigration.test.ts` 那道门禁止它们出现在活面上,
// 而这里只是举反例、不需要字面量;漂移实例逐条留档在 `TODOS.md` 与 CHANGELOG)。
// 还有一处更坏:把「Claude Code Agent Teams」改成「Codex Agent Teams」却照抄原机制 ——
// 名字本地化了机制没换,codex 根本没有 Agent Teams,只有 `spawn_agent`。
// 这正是 Phase 65 在 harnessed 自己正文里修掉的那类错,只是发生在手抄件上。
//
// 范围(维护者 2026-10-07 裁定「只放 harnessed 自己那段」):本模块只生成 harnessed **拥有真相源**
// 的内容 —— 命令清单、怎么进引擎、宿主原语对照。个人方法论(gstack 技能清单、三层栈路由偏好)
// 没有机器可读的源,harnessed 生成不了,留在标记区间**外**由维护者手写。
//
// 为什么不是「把 CLAUDE.md 渲染成 AGENTS.md」:Phase 65 的渲染器替换的是 `{{ host.* }}` 占位符,
// 而 CLAUDE.md 是自由散文、一个占位符都没有。要把散文里的 "Task tool" 自动换成 codex 说法就得做
// 盲替换,而 Phase 65 的教训恰恰是不能盲替换 —— 当时四个调用点是**重写**的,因为机械替换会产出
// 一条保证报错的指令(`agent_type: <sub>`,harnessed 还不为 sub 写 role toml)。
//
// 事实零手打:
//   * 命令清单 ← `scanWorkflowsNested` ∩ role-prompts(与 `writeAllCommands` 渲染的**同一个集合**)
//   * 原语对照 ← 直接嵌 `buildHostMapSection()` 的输出,不另造第二张表。嵌套 marker 是故意的:
//     这样 AGENTS.md 里那张表和 SKILL 正文里那张是同一个产物、同一个 yaml 源,不可能各自漂。
//   * caveat  ← `loadHostMapNotes()`(locale 感知)

import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { detectPlatform } from '../../platform/platform.js'
import { loadRolePrompts } from '../../workflow/rolePrompts.js'
import { scanWorkflowsNested } from '../../workflow/scan-nested.js'
import {
  buildHostMapSection,
  type HostPrimitiveTable,
  loadHostMapNotes,
  loadHostPrimitives,
} from './hostPrimitives.js'

/** 区间标记。与 host-map 的那对同形,但是不同字符串 —— 剥除按外层这对走,内层那对不受影响。 */
export const AGENTS_MD_START = '<!-- harnessed:agents-md:start -->'
export const AGENTS_MD_END = '<!-- harnessed:agents-md:end -->'

/** `<CODEX_HOME>/AGENTS.md`(codex 的 homeDir 就是 CODEX_HOME)。 */
export function agentsMdPath(): string {
  return join(detectPlatform().homeDir, 'AGENTS.md')
}

export interface AgentsMdSectionOptions {
  /** 已装命令名(排序后),与 `writeAllCommands` 的集合同源。 */
  commands: readonly string[]
  /** codex 的命令落位目录,用于告诉模型「这些是从哪读的」。 */
  commandsDir: string
  /** locale 选好的原语表。 */
  table: HostPrimitiveTable
  /** `host_map_notes.codex`。 */
  notes?: readonly string[]
}

/**
 * 生成区间内容(含首尾标记)。纯函数 —— 不碰 fs,便于对内容本身做断言。
 *
 * 命令清单只列名字不列描述:描述来自本地化的 role-prompts,而这段骨架是英文的;
 * 把中文描述塞进英文骨架正是 Phase 65 在 `prompt.description` 上修过的那个错。
 * 模型要描述可以读 `<commandsDir>/<name>.md` 的 frontmatter,那里本来就有。
 */
export function buildAgentsMdSection(opts: AgentsMdSectionOptions): string {
  const { commands, commandsDir, table } = opts
  const hostMap = buildHostMapSection({ host: 'codex', table, notes: opts.notes })
  const lines = [
    AGENTS_MD_START,
    '',
    '## harnessed',
    '',
    'This block is GENERATED by `harnessed agents-md`. Edits inside the markers are',
    'overwritten on the next run; put anything hand-written OUTSIDE them.',
    '',
    `harnessed installs its slash commands as prompt files under \`${commandsDir}\`.`,
    'Invoke one by name to enter the orchestration engine:',
    '',
    ...(commands.length > 0
      ? commands.map((c) => `- \`/${c}\``)
      : ['- (none installed — run `harnessed setup`)']),
    '',
    'Each command file carries its own description in frontmatter; read it there rather',
    'than guessing from the name.',
    '',
  ]
  // The host map is embedded verbatim, markers and all: the glossary in AGENTS.md is
  // then the SAME artifact as the one in every rendered SKILL body, off the same yaml.
  if (hostMap !== '') lines.push(hostMap.trimEnd(), '')
  lines.push(AGENTS_MD_END, '')
  return lines.join('\n')
}

/** 剥掉已有区间(含标记)。没有就原样返回。 */
export function stripAgentsMdSection(body: string): string {
  const a = body.indexOf(AGENTS_MD_START)
  if (a === -1) return body
  const b = body.indexOf(AGENTS_MD_END, a)
  if (b === -1) return body
  const head = body.slice(0, a)
  const tail = body.slice(b + AGENTS_MD_END.length)
  // 合并接缝处的空行,避免反复 insert/strip 把文件撑开
  return `${head.replace(/\n+$/, '\n')}${tail.replace(/^\n+/, '')}`
}

/**
 * 先剥后插 —— 幂等。区间追加在文件末尾:维护者手写的内容在前,生成的在后,
 * 这样 diff 只会动文件尾部。
 */
export function insertAgentsMdSection(body: string, section: string): string {
  const base = stripAgentsMdSection(body)
  if (section === '') return base
  const sep = base === '' || base.endsWith('\n\n') ? '' : base.endsWith('\n') ? '\n' : '\n\n'
  return `${base}${sep}${section}`
}

export interface AgentsMdDeps {
  readFile?: (p: string) => Promise<string>
  writeFile?: (p: string, c: string) => Promise<void>
}

/** 与 `writeAllCommands` 同源的命令集合:有 role-prompts 条目的已装 workflow,排序。 */
export async function resolveCommandNames(workflowsDir: string): Promise<string[]> {
  const { readdir } = await import('node:fs/promises')
  const entries = await readdir(workflowsDir)
  const { workflows } = await scanWorkflowsNested(workflowsDir, entries)
  const prompts = await loadRolePrompts(workflowsDir)
  return workflows
    .map((w) => w.name)
    .filter((n) => prompts[n] !== undefined)
    .sort()
}

/** 预览时文件会发生什么。`create` = 文件不存在,会新建。 */
export type AgentsMdAction = 'create' | 'append' | 'replace'

export type AgentsMdOutcome =
  | { status: 'written'; path: string; action: AgentsMdAction }
  | { status: 'unchanged'; path: string }
  | { status: 'removed'; path: string }
  | { status: 'absent'; path: string }
  /** `section` 只是**要写的那一段**,不是文件全文 —— 预览绝不把维护者的散文倒进终端。 */
  | { status: 'preview'; path: string; action: AgentsMdAction; section: string }

export interface RunAgentsMdOptions {
  workflowsDir: string
  /** true → 只算不写。 */
  dryRun?: boolean
  /** true → 剥除区间而非写入(卸载往返的另一半)。 */
  remove?: boolean
  locale?: 'en' | 'zh-Hans'
  deps?: AgentsMdDeps
}

/**
 * 算出目标文件应有的内容并(可选地)落盘。
 *
 * 文件不存在时:写入场景会**新建**一个只含区间的 AGENTS.md(codex 读得到才有意义);
 * 移除场景返回 `absent`,不创建空文件。
 */
export async function runAgentsMd(opts: RunAgentsMdOptions): Promise<AgentsMdOutcome> {
  const path = agentsMdPath()
  const read = opts.deps?.readFile ?? ((p: string) => readFile(p, 'utf8'))
  const write = opts.deps?.writeFile ?? ((p: string, c: string) => writeFile(p, c, 'utf8'))

  let current = ''
  let existed = true
  try {
    current = await read(path)
  } catch {
    existed = false
  }

  if (opts.remove === true) {
    if (!existed) return { status: 'absent', path }
    const next = stripAgentsMdSection(current)
    if (next === current) return { status: 'unchanged', path }
    if (opts.dryRun !== true) await write(path, next)
    return { status: 'removed', path }
  }

  const locale = opts.locale ?? 'en'
  const section = buildAgentsMdSection({
    commands: await resolveCommandNames(opts.workflowsDir),
    commandsDir: detectPlatform().commandsDir,
    table: await loadHostPrimitives({ workflowsDir: opts.workflowsDir, locale }),
    notes: await loadHostMapNotes({ workflowsDir: opts.workflowsDir, locale, host: 'codex' }),
  })
  const next = insertAgentsMdSection(current, section)
  if (existed && next === current) return { status: 'unchanged', path }
  // `action` 是给人看的那一句话:新建 / 追加 / 替换掉已有区间。
  const action: AgentsMdAction = !existed
    ? 'create'
    : current.includes(AGENTS_MD_START)
      ? 'replace'
      : 'append'
  // 预览只回传 section。早先回传过 `body`(文件全文),结果 dry-run 把维护者 192 行的
  // 个人指令整篇打进了终端 —— 既吵又越界:这个命令只对标记区间负责,就只该展示那一段。
  if (opts.dryRun === true) return { status: 'preview', path, action, section }
  await write(path, next)
  return { status: 'written', path, action }
}
